services:
  - type: web
    name: front-juntavecinal
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    nodeVersion: 18.18.0
    envVars:
      - key: NODE_ENV
        value: production